### ISSUE TITLE
Performance improvement suggestions

### ISSUE THREAD

**Issue by osavsunenko-ring** [shenwei356/bwt#3]
Dear shenwei,

If you'd like to get significant performance gains in your BWT you could switch to suffixarray from Go standard library. It operates in linear time, while you implementation doesn't. Here's a comparison  - https://github.com/crazyleg/burrow-wheelers-golang

**Comment by shenwei356** [comment]
Thank you so much, it's 4X faster!

```
$ benchcmp old.txt new.txt
benchmark                 old ns/op     new ns/op     delta
BenchmarkTransform-16     1339346       310706        -76.80%

benchmark                 old allocs     new allocs     delta
BenchmarkTransform-16     4              5              +25.00%

benchmark                 old bytes     new bytes     delta
BenchmarkTransform-16     55362         79962         +44.43%
```
